version: "~> 1.0"
language: php
dist: jammy
php:
- 8.3
services:
- docker
stages:
- lint
- test
- deploy
env:
  global:
  - DDEV_NO_INSTRUMENTATION=true
  # This is a dummy token, just to satisfy the conditions for testing.
  - ROLLBAR_SERVER_TOKEN=df6ce617465b4980afdecc95ed1b42de
  - PANTHEON_GIT_URL="ssh://codeserver.dev.f9006632-61ea-4266-8c4c-598eb325ef51@codeserver.dev.f9006632-61ea-4266-8c4c-598eb325ef51.drush.in:2222/~/repository.git"
  - secure: AAAAB3NzaC1yc2EAAAADAQABAAABgQDPE9jDDMJTMWJYWVPxFratmIrsZOYcUJcRqACV7gJ/7e+5YRyi9tAEv9hhL0yCVXcT5N3J/6MKM5glSthu/nno1+akCQ3F1H8utYGhyWGJf2dl242pRwT7SSZNdsC1gJSU4wEn4hfLIJaNIfEhfBLwfY6Cn0WSxzN8OEMxreHkObumKfazAeAMC6RylPADs5iqUWeJKKUtZ1/p0XPYPOOBV/ZrDYJz4ZbCCIgWi9TRRR33Dn8W99AzGGMnCV3ILmW82cONMRUF9Vw8KwxOb2RUpX6DwjkN33GZoeihTXZE4PiiTqJ27DJuU9s1I5MOlqDMZpFxvtNRqa7K7ny0MNKbm89AM2tnAyfwebuWuaf+4+tn4IUiJxai/b7NZD+2UiVPGke3yeKJRgQhRylyJ10WKTRcFNXGL34xoDp2W2tgADhGfe6at5kJCdfqf72bvndEyWGzVKvZnHrp9mCJx1JhVu+RY7Cf9IXl0T8ByuamqdEso01K3KwZWut56KCEgA8=
before_install:
- openssl aes-256-cbc -K $encrypted_2c02e48ad60e_key -iv $encrypted_2c02e48ad60e_iv
  -in travis-key.enc -out travis-key -d
- export PATH="$HOME/.config/composer/vendor/bin:$PATH"
git:
  depth: 500
jobs:
  allow_failures:
    env:
      - CAN_FAIL=true
  include:
  - stage: Lint
    name: PhpStan
    script:
    - "$TRAVIS_BUILD_DIR/ci-scripts/test_syntax.sh || travis_terminate 1;"
    - composer install
    - vendor/bin/phpstan analyse -c phpstan.neon
  - stage: Lint
    name: Drupal coding standard
    script:
    - composer install || travis_terminate 1;
    - vendor/bin/robo phpcs || travis_terminate 1;
  - stage: Lint
    name: 'Shell coding standard: shellcheck'
    script:
    - "$TRAVIS_BUILD_DIR/ci-scripts/install_shell.sh || travis_terminate 1;"
    - "$TRAVIS_BUILD_DIR/ci-scripts/test_shell.sh || travis_terminate 1;"
  - stage: Test
    name: 'Backend tests: Functional tests'
    if: (branch != "main" AND tag IS blank)
    script:
    - "(travis_retry $TRAVIS_BUILD_DIR/ci-scripts/install_ddev.sh) || travis_terminate 1;"
    - "$TRAVIS_BUILD_DIR/ci-scripts/install_drupal.sh || travis_terminate 1;"
    - "$TRAVIS_BUILD_DIR/ci-scripts/test_phpunit.sh || travis_terminate 1;"
    - "$TRAVIS_BUILD_DIR/ci-scripts/test_phpunit_rollbar.sh || travis_terminate 1;"
  - stage: Deploy
    env: CAN_FAIL=true
    name: 'Backend tests: Functional tests and deploy to Pantheon QA'
    if: branch = "main" AND type = push AND tag IS blank
    script:
    - "(travis_retry $TRAVIS_BUILD_DIR/ci-scripts/install_ddev.sh) || travis_terminate 1;"
    - "$TRAVIS_BUILD_DIR/ci-scripts/install_drupal.sh || travis_terminate 1;"
    - "$TRAVIS_BUILD_DIR/ci-scripts/test_phpunit.sh || travis_terminate 1;"
    - "(travis_retry $TRAVIS_BUILD_DIR/ci-scripts/prepare_deploy.sh) || travis_terminate 1;"
    - "(travis_retry ddev robo deploy:pantheon qa --no-interaction) || travis_terminate 1;"
    - ddev composer install || travis_terminate 1;
    - ddev robo deploy:notify || travis_terminate 1;
  - stage: Deploy
    name: 'Backend tests: Functional tests and deploy to Pantheon TEST'
    if: tag IS present AND type = "push" AND tag !~ /live$/
    script:
    - "(travis_retry $TRAVIS_BUILD_DIR/ci-scripts/install_ddev.sh) || travis_terminate 1;"
    - "$TRAVIS_BUILD_DIR/ci-scripts/install_drupal.sh || travis_terminate 1;"
    - "$TRAVIS_BUILD_DIR/ci-scripts/test_phpunit.sh || travis_terminate 1;"
    - "(travis_retry $TRAVIS_BUILD_DIR/ci-scripts/prepare_deploy.sh) || travis_terminate 1;"
    - "(travis_retry ddev robo deploy:tag-pantheon --no-interaction $TRAVIS_TAG master) || travis_terminate 1;"
    - ddev composer install || travis_terminate 1;
    - "(travis_retry ddev robo deploy:pantheon-sync) || travis_terminate 1;"
  - stage: Deploy
    name: 'Backend tests: Functional tests and deploy to Pantheon LIVE'
    if: tag IS present AND type = "push" AND tag =~ /live$/
    script:
    - "$TRAVIS_BUILD_DIR/ci-scripts/check_live_deploy.sh || travis_terminate 1;"
    - "(travis_retry $TRAVIS_BUILD_DIR/ci-scripts/install_ddev.sh) || travis_terminate 1;"
    - "$TRAVIS_BUILD_DIR/ci-scripts/install_drupal.sh || travis_terminate 1;"
    - "$TRAVIS_BUILD_DIR/ci-scripts/test_phpunit.sh || travis_terminate 1;"
    - "(travis_retry $TRAVIS_BUILD_DIR/ci-scripts/prepare_deploy.sh) || travis_terminate 1;"
    - "(travis_retry ddev robo deploy:pantheon-sync live) || travis_terminate 1;"
